import type { Metadata } from "next";
import { Playfair_Display, DM_Sans } from "next/font/google";
import "./globals.css";
import { SEO } from "@/lib/seo";
import JsonLd from "@/components/seo/JsonLd";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata: Metadata = {
  /**
   * metadataBase enables automatic canonical URL resolution
   * for all pages in the app. Also required for OG images.
   */
  metadataBase: new URL(SEO.SITE_URL),

  /**
   * Title template — every child page gets ` | Brunēa` appended.
   * The `default` is used when a page doesn't set its own title.
   */
  title: {
    default: `${SEO.SITE_NAME} | ${SEO.TAGLINE}`,
    template: `%s | ${SEO.SITE_NAME}`,
  },

  description: SEO.SITE_DESCRIPTION,
  keywords: [...SEO.KEYWORDS],

  /** Canonical URL + language alternates */
  alternates: {
    canonical: "/",
  },

  /** Tell crawlers to index with generous snippet/image previews */
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  /** Full Open Graph metadata for rich social sharing */
  openGraph: {
    type: "website",
    locale: "es_PE",
    url: SEO.SITE_URL,
    siteName: SEO.SITE_NAME,
    title: `${SEO.SITE_NAME} — ${SEO.TAGLINE}`,
    description: SEO.SITE_DESCRIPTION,
    // OG image is auto-generated by app/opengraph-image.tsx
  },

  /** Twitter / X card for sharing */
  twitter: {
    card: "summary_large_image",
    title: `${SEO.SITE_NAME} — ${SEO.TAGLINE}`,
    description: SEO.SITE_DESCRIPTION,
    // Twitter image inherits from OG image
  },

  /** App categorization for search engines */
  category: "Shopping",
  creator: SEO.SITE_NAME,
  publisher: SEO.SITE_NAME,
};

/**
 * Organization + LocalBusiness JSON-LD — injected at root level.
 * Tells Google: who we are, where we are, how to contact us,
 * and our social media presence.
 */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": ["Organization", "LocalBusiness"],
  name: SEO.SITE_NAME,
  description: SEO.SITE_DESCRIPTION,
  url: SEO.SITE_URL,
  logo: `${SEO.SITE_URL}/favicon.ico`,
  image: `${SEO.SITE_URL}/opengraph-image`,
  telephone: `+${SEO.WHATSAPP_NUMBER}`,
  address: {
    "@type": "PostalAddress",
    addressLocality: SEO.LOCATION.city,
    addressRegion: SEO.LOCATION.region,
    addressCountry: SEO.LOCATION.country,
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: -8.1116,
    longitude: -79.0289,
  },
  areaServed: {
    "@type": "Country",
    name: SEO.LOCATION.countryName,
  },
  priceRange: "$$",
  currenciesAccepted: SEO.CURRENCY,
  paymentAccepted: "Transferencia bancaria, Yape, Plin",
  sameAs: [SEO.SOCIAL.instagram, SEO.SOCIAL.tiktok],
  contactPoint: {
    "@type": "ContactPoint",
    telephone: `+${SEO.WHATSAPP_NUMBER}`,
    contactType: "sales",
    availableLanguage: "Spanish",
  },
};

/**
 * WebSite JSON-LD — enables sitelinks search box in Google
 * and clarifies the site structure.
 */
const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SEO.SITE_NAME,
  url: SEO.SITE_URL,
  description: SEO.SITE_DESCRIPTION,
  inLanguage: "es",
  publisher: {
    "@type": "Organization",
    name: SEO.SITE_NAME,
    url: SEO.SITE_URL,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${playfair.variable} ${dmSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Structured data for search engines */}
        <JsonLd data={organizationJsonLd} />
        <JsonLd data={websiteJsonLd} />
        {children}
      </body>
    </html>
  );
}
